import { createHash } from "node:crypto";
import { prisma } from "@/lib/prisma";
import { getGeoGridEnv } from "@/lib/env";
import { AppError } from "@/lib/errors";
import { generateGrid } from "./grid";
import { checkSpendPolicy } from "./cost";
import { createDataForSeoClient, type DataForSeoClient, type SubmittedTask } from "./dataforseo";
import { calculateScanMetrics, compareScans } from "./metrics";
import { matchTarget, normalizeCompetitors, type ProviderMapResult } from "./matching";
import type { GridPoint } from "./types";

type Target={location:{id:string;googleLocationId:string;mapsPlaceId?:string|null;title:string;address:string|null;latitude:number|null;longitude:number|null;status:string;isTrackingActive:boolean};keyword:{id:string;displayKeyword:string;state:string;defaultGridSize:number;radiusKm:number;languageCode:string}};
type ScanInput={locationId:string;keywordId:string;gridSize?:number;radiusKm?:number};
type NewScan={fingerprint:string;target:Target;points:GridPoint[];estimatedCostUsd:number;origin:"MANUAL"|"SCHEDULED"|"RETRY";providerMethod:string;config:{size:number;radiusKm:number}};
type ScanRepo={getTarget(locationId:string,keywordId:string):Promise<Target|null>;findByFingerprint(value:string):Promise<unknown|null>;getSpend(now:Date):Promise<{weekMicroUsd:number;monthMicroUsd:number}>;create(input:NewScan):Promise<{id:string}>;saveSubmitted(scanId:string,points:Array<GridPoint&{providerTaskId:string;costUsd:number}>):Promise<unknown>};

function weekKey(date:Date){const value=new Date(Date.UTC(date.getUTCFullYear(),date.getUTCMonth(),date.getUTCDate()));const day=(value.getUTCDay()+6)%7;value.setUTCDate(value.getUTCDate()-day);return value.toISOString().slice(0,10);}
const productionRepo:ScanRepo={
  async getTarget(locationId,keywordId){const location=await prisma.businessLocation.findUnique({where:{googleLocationId:locationId}});if(!location)return null;const keyword=await prisma.trackedKeyword.findFirst({where:{id:keywordId,businessLocationId:location.id}});return keyword?{location,keyword}:null;},
  async findByFingerprint(fingerprint){return await prisma.geoGridScan.findUnique({where:{fingerprint},include:{points:true}});},
  async getSpend(now){const week=new Date(`${weekKey(now)}T00:00:00Z`),month=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),1));const [weekly,monthly]=await Promise.all([prisma.providerSpend.aggregate({_sum:{amountUsd:true},where:{incurredAt:{gte:week}}}),prisma.providerSpend.aggregate({_sum:{amountUsd:true},where:{incurredAt:{gte:month}}})]);return{weekMicroUsd:Math.round(Number(weekly._sum.amountUsd??0)*1e6),monthMicroUsd:Math.round(Number(monthly._sum.amountUsd??0)*1e6)};},
  async create(input){return await prisma.geoGridScan.create({data:{businessLocationId:input.target.location.id,trackedKeywordId:input.target.keyword.id,fingerprint:input.fingerprint,keyword:input.target.keyword.displayKeyword,centerLatitude:input.target.location.latitude!,centerLongitude:input.target.location.longitude!,gridSize:input.config.size,radiusKm:input.config.radiusKm,languageCode:input.target.keyword.languageCode,providerMethod:input.providerMethod,origin:input.origin,status:"SUBMITTING",pointCount:input.points.length,estimatedCostUsd:input.estimatedCostUsd,points:{create:input.points.map(point=>({...point}))}}});},
  async saveSubmitted(scanId,points){return await prisma.$transaction(async tx=>{for(const point of points)await tx.geoGridPoint.update({where:{scanId_row_column:{scanId,row:point.row,column:point.column}},data:{providerTaskId:point.providerTaskId,status:"SUBMITTED",costUsd:point.costUsd}});const costs=await tx.geoGridPoint.aggregate({_sum:{costUsd:true},where:{scanId}});const actualCostUsd=Number(costs._sum.costUsd??0);return await tx.geoGridScan.update({where:{id:scanId},data:{status:"RUNNING",startedAt:new Date(),actualCostUsd}});});},
};
function provider(){const env=getGeoGridEnv();return createDataForSeoClient({login:env.DATAFORSEO_LOGIN,password:env.DATAFORSEO_PASSWORD,fetchImpl:fetch});}

async function reserveProduction(input:NewScan,limits:{maxScanMicroUsd:number;weeklyLimitMicroUsd:number;monthlyLimitMicroUsd:number},now:Date){
  try{return await prisma.$transaction(async tx=>{const existing=await tx.geoGridScan.findUnique({where:{fingerprint:input.fingerprint},include:{points:true}});if(existing)return{scan:existing,created:false};const week=new Date(`${weekKey(now)}T00:00:00Z`),month=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),1));const [weekly,monthly]=await Promise.all([tx.providerSpend.aggregate({_sum:{amountUsd:true},where:{incurredAt:{gte:week}}}),tx.providerSpend.aggregate({_sum:{amountUsd:true},where:{incurredAt:{gte:month}}})]);const estimatedMicroUsd=Math.round(input.estimatedCostUsd*1e6),decision=checkSpendPolicy({spentWeekMicroUsd:Math.round(Number(weekly._sum.amountUsd??0)*1e6),spentMonthMicroUsd:Math.round(Number(monthly._sum.amountUsd??0)*1e6),estimatedMicroUsd,...limits});if(!decision.allowed)throw new AppError("QUOTA_EXCEEDED","COST_LIMIT_EXCEEDED");const scan=await tx.geoGridScan.create({data:{businessLocationId:input.target.location.id,trackedKeywordId:input.target.keyword.id,fingerprint:input.fingerprint,keyword:input.target.keyword.displayKeyword,centerLatitude:input.target.location.latitude!,centerLongitude:input.target.location.longitude!,gridSize:input.config.size,radiusKm:input.config.radiusKm,languageCode:input.target.keyword.languageCode,providerMethod:input.providerMethod,origin:input.origin,status:"SUBMITTING",pointCount:input.points.length,estimatedCostUsd:input.estimatedCostUsd,points:{create:input.points.map(point=>({...point}))}}});await tx.providerSpend.create({data:{scanId:scan.id,amountUsd:input.estimatedCostUsd}});return{scan,created:true};},{isolationLevel:"Serializable"});}catch(error){const existing=await prisma.geoGridScan.findUnique({where:{fingerprint:input.fingerprint},include:{points:true}});if(existing)return{scan:existing,created:false};throw error;}}

export async function createScan(input:ScanInput,origin:"MANUAL"|"SCHEDULED"|"RETRY",deps?:{repo:ScanRepo;provider:Pick<DataForSeoClient,"submitMapTasks">;limits:{maxScanMicroUsd:number;weeklyLimitMicroUsd:number;monthlyLimitMicroUsd:number};pricePerTaskMicroUsd:number;now:()=>Date}){
  const env=deps?null:getGeoGridEnv(),repo=deps?.repo??productionRepo,api=deps?.provider??provider(),now=deps?.now()??new Date(),limits=deps?.limits??{maxScanMicroUsd:Math.round(env!.GEOGRID_MAX_SCAN_USD*1e6),weeklyLimitMicroUsd:Math.round(env!.GEOGRID_WEEKLY_LIMIT_USD*1e6),monthlyLimitMicroUsd:Math.round(env!.GEOGRID_MONTHLY_LIMIT_USD*1e6)},price=deps?.pricePerTaskMicroUsd??600;
  const target=await repo.getTarget(input.locationId,input.keywordId);if(!target||target.keyword.state!=="APPROVED")throw new AppError("INVALID_INPUT");if(target.location.status!=="OPEN"||target.location.latitude===null||target.location.longitude===null)throw new AppError("INVALID_INPUT");
  const config={centerLat:target.location.latitude,centerLng:target.location.longitude,size:input.gridSize??target.keyword.defaultGridSize,radiusKm:input.radiusKm??target.keyword.radiusKm},points=generateGrid(config),fingerprint=createHash("sha256").update(JSON.stringify({location:target.location.id,keyword:target.keyword.id,...config,language:target.keyword.languageCode,method:"standard",week:weekKey(now)})).digest("hex"),existing=await repo.findByFingerprint(fingerprint);if(existing)return existing;
  const estimatedMicroUsd=points.length*price,newScan={fingerprint,target,points,estimatedCostUsd:estimatedMicroUsd/1e6,origin,providerMethod:"standard",config:{size:config.size,radiusKm:config.radiusKm}} as const;let scan:{id:string};if(deps){const spend=await repo.getSpend(now),decision=checkSpendPolicy({spentWeekMicroUsd:spend.weekMicroUsd,spentMonthMicroUsd:spend.monthMicroUsd,estimatedMicroUsd,...limits});if(!decision.allowed)throw new AppError("QUOTA_EXCEEDED","COST_LIMIT_EXCEEDED");scan=await repo.create(newScan);}else{const reservation=await reserveProduction(newScan,limits,now);if(!reservation.created)return reservation.scan;scan=reservation.scan;}let result:unknown=scan,totalCost=0;try{for(let offset=0;offset<points.length;offset+=100){const batch=points.slice(offset,offset+100),submitted:SubmittedTask[]=await api.submitMapTasks(batch.map(point=>({keyword:target.keyword.displayKeyword,languageCode:target.keyword.languageCode,latitude:point.latitude,longitude:point.longitude,depth:20})));totalCost+=submitted.reduce((sum,item)=>sum+item.costUsd,0);result=await repo.saveSubmitted(scan.id,batch.map((point,index)=>({...point,providerTaskId:submitted[index].id,costUsd:submitted[index].costUsd})));}if(!deps){const spend=await prisma.providerSpend.findFirstOrThrow({where:{scanId:scan.id},orderBy:{incurredAt:"asc"}});await prisma.providerSpend.update({where:{id:spend.id},data:{amountUsd:totalCost}});}return result;}catch(error){if(!deps)await prisma.geoGridScan.update({where:{id:scan.id},data:{status:"FAILED",failureCode:"SUBMISSION_FAILED"}});throw error;}
}
export async function getScan(scanId:string){const scan=await prisma.geoGridScan.findUnique({where:{id:scanId},include:{points:{include:{competitors:true},orderBy:[{row:"asc"},{column:"asc"}]},businessLocation:true}});if(!scan)throw new AppError("INVALID_INPUT");const points=scan.points.map(point=>({row:point.row,column:point.column,latitude:point.latitude,longitude:point.longitude,status:point.status,rank:point.targetRank,matchConfidence:point.matchConfidence,failureCode:point.failureCode,competitors:point.competitors}));return{...scan,businessLocation:{title:scan.businessLocation.title,address:scan.businessLocation.address},estimatedCostUsd:Number(scan.estimatedCostUsd),actualCostUsd:Number(scan.actualCostUsd),points,metrics:calculateScanMetrics(points.map(point=>({row:point.row,column:point.column,latitude:point.latitude,longitude:point.longitude,status:point.status==="COMPLETE"?"COMPLETE" as const:"FAILED" as const,rank:point.rank})))};}
export async function listScans(locationId:string,keywordId?:string){const location=await prisma.businessLocation.findUnique({where:{googleLocationId:locationId}});if(!location)throw new AppError("INVALID_INPUT");return await prisma.geoGridScan.findMany({where:{businessLocationId:location.id,...(keywordId?{trackedKeywordId:keywordId}:{})},select:{id:true,keyword:true,status:true,gridSize:true,radiusKm:true,createdAt:true,completedAt:true,actualCostUsd:true},orderBy:{createdAt:"desc"},take:50});}
export async function compareScanReports(currentId:string,previousId:string){const [current,previous]=await Promise.all([getScan(currentId),getScan(previousId)]);if(current.businessLocationId!==previous.businessLocationId||current.trackedKeywordId!==previous.trackedKeywordId||current.gridSize!==previous.gridSize||current.radiusKm!==previous.radiusKm||current.centerLatitude!==previous.centerLatitude||current.centerLongitude!==previous.centerLongitude||current.languageCode!==previous.languageCode)throw new AppError("INVALID_INPUT");const comparison=compareScans(current.points.map(point=>({row:point.row,column:point.column,latitude:point.latitude,longitude:point.longitude,status:point.status==="COMPLETE"?"COMPLETE" as const:"FAILED" as const,rank:point.rank})),previous.points.map(point=>({row:point.row,column:point.column,latitude:point.latitude,longitude:point.longitude,status:point.status==="COMPLETE"?"COMPLETE" as const:"FAILED" as const,rank:point.rank})));if(!comparison)throw new AppError("INVALID_INPUT");const changes=new Map(comparison.points.map(point=>[`${point.row}:${point.column}`,point]));return{...current,points:current.points.map(point=>({...point,previousRank:changes.get(`${point.row}:${point.column}`)?.previousRank,change:changes.get(`${point.row}:${point.column}`)?.change}))};}
type AdvanceResult={pointId:string;status:"COMPLETE"|"RUNNING"|"FAILED";rank?:number|null;confidence?:"EXACT"|"FALLBACK";placeId?:string|null;failureCode?:string;competitors?:ReturnType<typeof normalizeCompetitors>};
type AdvanceRepo={getSubmitted(scanId:string):Promise<{target:{name:string;address:string|null;placeId:string|null};points:Array<{id:string;providerTaskId:string}>}>;saveResults(scanId:string,results:AdvanceResult[]):Promise<unknown>};
const productionAdvanceRepo:AdvanceRepo={
  async getSubmitted(scanId){const scan=await prisma.geoGridScan.findUnique({where:{id:scanId},include:{businessLocation:true,points:{where:{status:"SUBMITTED",providerTaskId:{not:null}}}}});if(!scan)throw new AppError("INVALID_INPUT");return{target:{name:scan.businessLocation.title,address:scan.businessLocation.address,placeId:scan.businessLocation.mapsPlaceId},points:scan.points.map(point=>({id:point.id,providerTaskId:point.providerTaskId!}))};},
  async saveResults(scanId,results){return await prisma.$transaction(async tx=>{for(const result of results){if(result.status==="RUNNING")continue;await tx.geoGridCompetitor.deleteMany({where:{pointId:result.pointId}});const retryable=result.status==="FAILED"&&result.failureCode?.startsWith("5");await tx.geoGridPoint.update({where:{id:result.pointId},data:{status:result.status==="COMPLETE"?"COMPLETE":retryable?"RETRYABLE_FAILED":"PERMANENT_FAILED",failureCode:result.failureCode,targetRank:result.rank,targetPlaceId:result.placeId,matchConfidence:result.confidence,competitors:result.competitors?.length?{create:result.competitors}:undefined}});}const counts=await tx.geoGridPoint.groupBy({by:["status"],where:{scanId},_count:true});const count=(status:string)=>counts.find(entry=>entry.status===status)?._count??0,complete=count("COMPLETE"),failed=count("RETRYABLE_FAILED")+count("PERMANENT_FAILED"),pending=count("PENDING")+count("SUBMITTED");return await tx.geoGridScan.update({where:{id:scanId},data:{completedCount:complete,failedCount:failed,status:pending?"RUNNING":failed?"PARTIAL":"COMPLETE",completedAt:pending?null:new Date()}});});},
};
export async function advanceScan(scanId:string,deps?:{repo:AdvanceRepo;provider:Pick<DataForSeoClient,"getMapTasks">}){const repo=deps?.repo??productionAdvanceRepo,api=deps?.provider??provider(),pending=await repo.getSubmitted(scanId);if(!pending.points.length)return deps?await repo.saveResults(scanId,[]):await getScan(scanId);const tasks=await api.getMapTasks(pending.points.map(point=>point.providerTaskId)),byId=new Map(pending.points.map(point=>[point.providerTaskId,point.id]));const results:AdvanceResult[]=tasks.map(task=>{const pointId=byId.get(task.id)!;if(task.status!=="COMPLETE")return{pointId,status:task.status,failureCode:task.failureCode};const items=task.items as ProviderMapResult[],match=matchTarget(items,pending.target);return{pointId,status:"COMPLETE",rank:match?.rank??null,confidence:match?.confidence,placeId:match?.placeId??null,competitors:normalizeCompetitors(items)};});return await repo.saveResults(scanId,results);}
export async function retryFailedPoints(scanId:string){const scan=await prisma.geoGridScan.findUnique({where:{id:scanId},include:{points:{where:{status:{in:["RETRYABLE_FAILED","PENDING"]},retryCount:{lt:3}}},trackedKeyword:true}});if(!scan||!scan.points.length)throw new AppError("INVALID_INPUT");const env=getGeoGridEnv(),estimatedMicroUsd=scan.points.length*600,now=new Date();const reservation=await prisma.$transaction(async tx=>{const week=new Date(`${weekKey(now)}T00:00:00Z`),month=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),1));const [weekly,monthly]=await Promise.all([tx.providerSpend.aggregate({_sum:{amountUsd:true},where:{incurredAt:{gte:week}}}),tx.providerSpend.aggregate({_sum:{amountUsd:true},where:{incurredAt:{gte:month}}})]);const decision=checkSpendPolicy({spentWeekMicroUsd:Math.round(Number(weekly._sum.amountUsd??0)*1e6),spentMonthMicroUsd:Math.round(Number(monthly._sum.amountUsd??0)*1e6),estimatedMicroUsd,maxScanMicroUsd:Math.round(env.GEOGRID_MAX_SCAN_USD*1e6),weeklyLimitMicroUsd:Math.round(env.GEOGRID_WEEKLY_LIMIT_USD*1e6),monthlyLimitMicroUsd:Math.round(env.GEOGRID_MONTHLY_LIMIT_USD*1e6)});if(!decision.allowed)throw new AppError("QUOTA_EXCEEDED","COST_LIMIT_EXCEEDED");const spend=await tx.providerSpend.create({data:{scanId,amountUsd:estimatedMicroUsd/1e6}});await tx.geoGridPoint.updateMany({where:{id:{in:scan.points.map(point=>point.id)}},data:{status:"PENDING",providerTaskId:null,retryCount:{increment:1}}});return spend;},{isolationLevel:"Serializable"});const requests=scan.points.map(point=>({keyword:scan.keyword,languageCode:scan.languageCode,latitude:point.latitude,longitude:point.longitude,depth:20}));let totalCost=0;for(let offset=0;offset<requests.length;offset+=100){const batchPoints=scan.points.slice(offset,offset+100),submitted=await provider().submitMapTasks(requests.slice(offset,offset+100));totalCost+=submitted.reduce((sum,item)=>sum+item.costUsd,0);await productionRepo.saveSubmitted(scanId,batchPoints.map((point,index)=>({row:point.row,column:point.column,latitude:point.latitude,longitude:point.longitude,providerTaskId:submitted[index].id,costUsd:submitted[index].costUsd})));}await prisma.providerSpend.update({where:{id:reservation.id},data:{amountUsd:totalCost}});return await getScan(scanId);}
