import { createHash } from "node:crypto";
import { prisma } from "@/lib/prisma";
import { getEnv } from "@/lib/env";
import { AppError } from "@/lib/errors";
import { generateGrid } from "./grid";
import { checkSpendPolicy } from "./cost";
import { createDataForSeoClient, type DataForSeoClient, type SubmittedTask } from "./dataforseo";
import { calculateScanMetrics } from "./metrics";
import { matchTarget, normalizeCompetitors, type ProviderMapResult } from "./matching";
import type { GridPoint } from "./types";

type Target={location:{id:string;googleLocationId:string;title:string;address:string|null;latitude:number|null;longitude:number|null;status:string;isTrackingActive:boolean};keyword:{id:string;displayKeyword:string;state:string;defaultGridSize:number;radiusKm:number;languageCode:string}};
type ScanInput={locationId:string;keywordId:string;gridSize?:number;radiusKm?:number};
type NewScan={fingerprint:string;target:Target;points:GridPoint[];estimatedCostUsd:number;origin:"MANUAL"|"SCHEDULED"|"RETRY";providerMethod:string};
type ScanRepo={getTarget(locationId:string,keywordId:string):Promise<Target|null>;findByFingerprint(value:string):Promise<unknown|null>;getSpend(now:Date):Promise<{weekMicroUsd:number;monthMicroUsd:number}>;create(input:NewScan):Promise<{id:string}>;saveSubmitted(scanId:string,points:Array<GridPoint&{providerTaskId:string;costUsd:number}>):Promise<unknown>};

function weekKey(date:Date){const value=new Date(Date.UTC(date.getUTCFullYear(),date.getUTCMonth(),date.getUTCDate()));const day=(value.getUTCDay()+6)%7;value.setUTCDate(value.getUTCDate()-day);return value.toISOString().slice(0,10);}
const productionRepo:ScanRepo={
  async getTarget(locationId,keywordId){const location=await prisma.businessLocation.findUnique({where:{googleLocationId:locationId}});if(!location)return null;const keyword=await prisma.trackedKeyword.findFirst({where:{id:keywordId,businessLocationId:location.id}});return keyword?{location,keyword}:null;},
  async findByFingerprint(fingerprint){return await prisma.geoGridScan.findUnique({where:{fingerprint},include:{points:true}});},
  async getSpend(now){const week=new Date(`${weekKey(now)}T00:00:00Z`),month=new Date(Date.UTC(now.getUTCFullYear(),now.getUTCMonth(),1));const [weekly,monthly]=await Promise.all([prisma.providerSpend.aggregate({_sum:{amountUsd:true},where:{incurredAt:{gte:week}}}),prisma.providerSpend.aggregate({_sum:{amountUsd:true},where:{incurredAt:{gte:month}}})]);return{weekMicroUsd:Math.round(Number(weekly._sum.amountUsd??0)*1e6),monthMicroUsd:Math.round(Number(monthly._sum.amountUsd??0)*1e6)};},
  async create(input){return await prisma.geoGridScan.create({data:{businessLocationId:input.target.location.id,trackedKeywordId:input.target.keyword.id,fingerprint:input.fingerprint,keyword:input.target.keyword.displayKeyword,centerLatitude:input.target.location.latitude!,centerLongitude:input.target.location.longitude!,gridSize:Math.sqrt(input.points.length),radiusKm:input.target.keyword.radiusKm,languageCode:input.target.keyword.languageCode,providerMethod:input.providerMethod,origin:input.origin,status:"SUBMITTING",pointCount:input.points.length,estimatedCostUsd:input.estimatedCostUsd,points:{create:input.points.map(point=>({...point}))}}});},
  async saveSubmitted(scanId,points){return await prisma.$transaction(async tx=>{for(const point of points)await tx.geoGridPoint.update({where:{scanId_row_column:{scanId,row:point.row,column:point.column}},data:{providerTaskId:point.providerTaskId,status:"SUBMITTED",costUsd:point.costUsd}});const actualCostUsd=points.reduce((sum,p)=>sum+p.costUsd,0);await tx.providerSpend.create({data:{scanId,amountUsd:actualCostUsd}});return await tx.geoGridScan.update({where:{id:scanId},data:{status:"RUNNING",startedAt:new Date(),actualCostUsd}});});},
};
function provider(){const env=getEnv();return createDataForSeoClient({login:env.DATAFORSEO_LOGIN,password:env.DATAFORSEO_PASSWORD,fetchImpl:fetch});}

export async function createScan(input:ScanInput,origin:"MANUAL"|"SCHEDULED"|"RETRY",deps?:{repo:ScanRepo;provider:Pick<DataForSeoClient,"submitMapTasks">;limits:{maxScanMicroUsd:number;weeklyLimitMicroUsd:number;monthlyLimitMicroUsd:number};pricePerTaskMicroUsd:number;now:()=>Date}){
  const env=deps?null:getEnv(),repo=deps?.repo??productionRepo,api=deps?.provider??provider(),now=deps?.now()??new Date(),limits=deps?.limits??{maxScanMicroUsd:Math.round(env!.GEOGRID_MAX_SCAN_USD*1e6),weeklyLimitMicroUsd:Math.round(env!.GEOGRID_WEEKLY_LIMIT_USD*1e6),monthlyLimitMicroUsd:Math.round(env!.GEOGRID_MONTHLY_LIMIT_USD*1e6)},price=deps?.pricePerTaskMicroUsd??600;
  const target=await repo.getTarget(input.locationId,input.keywordId);if(!target||target.keyword.state!=="APPROVED")throw new AppError("INVALID_INPUT");if(target.location.status!=="OPEN"||target.location.latitude===null||target.location.longitude===null)throw new AppError("INVALID_INPUT");
  const config={centerLat:target.location.latitude,centerLng:target.location.longitude,size:input.gridSize??target.keyword.defaultGridSize,radiusKm:input.radiusKm??target.keyword.radiusKm},points=generateGrid(config),fingerprint=createHash("sha256").update(JSON.stringify({location:target.location.id,keyword:target.keyword.id,...config,language:target.keyword.languageCode,method:"standard",week:weekKey(now)})).digest("hex"),existing=await repo.findByFingerprint(fingerprint);if(existing)return existing;
  const estimatedMicroUsd=points.length*price,spend=await repo.getSpend(now),decision=checkSpendPolicy({spentWeekMicroUsd:spend.weekMicroUsd,spentMonthMicroUsd:spend.monthMicroUsd,estimatedMicroUsd,...limits});if(!decision.allowed)throw new AppError("QUOTA_EXCEEDED","COST_LIMIT_EXCEEDED");
  const scan=await repo.create({fingerprint,target,points,estimatedCostUsd:estimatedMicroUsd/1e6,origin,providerMethod:"standard"});const submitted:SubmittedTask[]=await api.submitMapTasks(points.map(point=>({keyword:target.keyword.displayKeyword,languageCode:target.keyword.languageCode,latitude:point.latitude,longitude:point.longitude,depth:20})));return await repo.saveSubmitted(scan.id,points.map((point,index)=>({...point,providerTaskId:submitted[index].id,costUsd:submitted[index].costUsd})));
}
export async function getScan(scanId:string){const scan=await prisma.geoGridScan.findUnique({where:{id:scanId},include:{points:{include:{competitors:true},orderBy:[{row:"asc"},{column:"asc"}]}}});if(!scan)throw new AppError("INVALID_INPUT");const points=scan.points.map(point=>({row:point.row,column:point.column,latitude:point.latitude,longitude:point.longitude,status:point.status==="COMPLETE"?"COMPLETE" as const:"FAILED" as const,rank:point.targetRank,competitors:point.competitors}));return{...scan,estimatedCostUsd:Number(scan.estimatedCostUsd),actualCostUsd:Number(scan.actualCostUsd),points,metrics:calculateScanMetrics(points)};}
type AdvanceResult={pointId:string;status:"COMPLETE"|"RUNNING"|"FAILED";rank?:number|null;confidence?:"EXACT"|"FALLBACK";placeId?:string|null;competitors?:ReturnType<typeof normalizeCompetitors>};
type AdvanceRepo={getSubmitted(scanId:string):Promise<{target:{name:string;address:string|null;placeId:string|null};points:Array<{id:string;providerTaskId:string}>}>;saveResults(scanId:string,results:AdvanceResult[]):Promise<unknown>};
const productionAdvanceRepo:AdvanceRepo={
  async getSubmitted(scanId){const scan=await prisma.geoGridScan.findUnique({where:{id:scanId},include:{businessLocation:true,points:{where:{status:"SUBMITTED",providerTaskId:{not:null}}}}});if(!scan)throw new AppError("INVALID_INPUT");return{target:{name:scan.businessLocation.title,address:scan.businessLocation.address,placeId:null},points:scan.points.map(point=>({id:point.id,providerTaskId:point.providerTaskId!}))};},
  async saveResults(scanId,results){return await prisma.$transaction(async tx=>{for(const result of results){if(result.status==="RUNNING")continue;await tx.geoGridCompetitor.deleteMany({where:{pointId:result.pointId}});await tx.geoGridPoint.update({where:{id:result.pointId},data:{status:result.status==="COMPLETE"?"COMPLETE":"RETRYABLE_FAILED",targetRank:result.rank,targetPlaceId:result.placeId,matchConfidence:result.confidence,competitors:result.competitors?.length?{create:result.competitors}:undefined}});}const counts=await tx.geoGridPoint.groupBy({by:["status"],where:{scanId},_count:true});const count=(status:string)=>counts.find(entry=>entry.status===status)?._count??0,complete=count("COMPLETE"),failed=count("RETRYABLE_FAILED")+count("PERMANENT_FAILED"),pending=count("PENDING")+count("SUBMITTED");return await tx.geoGridScan.update({where:{id:scanId},data:{completedCount:complete,failedCount:failed,status:pending?"RUNNING":failed?"PARTIAL":"COMPLETE",completedAt:pending?null:new Date()}});});},
};
export async function advanceScan(scanId:string,deps?:{repo:AdvanceRepo;provider:Pick<DataForSeoClient,"getMapTasks">}){const repo=deps?.repo??productionAdvanceRepo,api=deps?.provider??provider(),pending=await repo.getSubmitted(scanId);if(!pending.points.length)return await getScan(scanId);const tasks=await api.getMapTasks(pending.points.map(point=>point.providerTaskId)),byId=new Map(pending.points.map(point=>[point.providerTaskId,point.id]));const results:AdvanceResult[]=tasks.map(task=>{const pointId=byId.get(task.id)!;if(task.status!=="COMPLETE")return{pointId,status:task.status};const items=task.items as ProviderMapResult[],match=matchTarget(items,pending.target);return{pointId,status:"COMPLETE",rank:match?.rank??null,confidence:match?.confidence,placeId:match?.placeId??null,competitors:normalizeCompetitors(items)};});return await repo.saveResults(scanId,results);}
export async function retryFailedPoints(scanId:string){return await getScan(scanId);}
