"use client";
import { useEffect, useState } from "react";
import { ReportState } from "./report-state";
import type { ReportData } from "./performance/types";

type Property = { id: string; label: string; type: string };
export function PropertyPicker({ onChange }: { onChange?: (value: string) => void }) {
  const [items,setItems]=useState<Property[]>([]); const [error,setError]=useState("");
  useEffect(()=>{fetch('/api/properties').then(r=>r.json()).then(v=>v.data?setItems(v.data):setError(v.error)).catch(()=>setError('Unable to load properties.'))},[]);
  return <div className="property-picker"><label title="Choose which verified Search Console website supplies this report">Search Console property<select aria-label="Search Console property" title="Choose a website property" onChange={e=>onChange?.(e.target.value)} defaultValue=""><option value="" disabled>{items.length?'Choose a property':'No property selected'}</option>{items.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label>{error&&<LinkConnect message={error}/>}</div>;
}
function LinkConnect({message}:{message:string}) { return <p className="inline-error">{message} <a href="/settings">Connect Google</a></p> }
export function readOverviewPerformance(value: unknown): ReportData {
  if (!value || typeof value !== "object" || !("summary" in value) || !("rows" in value) || !Array.isArray((value as ReportData).rows)) throw new Error("Invalid performance response");
  return value as ReportData;
}
export function PerformancePanel({ compact=false }:{compact?:boolean}) {
  const [rows,setRows]=useState<Array<{key:string;clicks:number;impressions:number;ctr:number;position:number}>>([]); const [summary,setSummary]=useState({clicks:0,impressions:0,ctr:0,position:0}); const [status,setStatus]=useState('idle');
  async function load(p:string){const end=new Date();const start=new Date(end);start.setDate(start.getDate()-27);setStatus('loading');try{const r=await fetch('/api/performance',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({property:p,startDate:start.toISOString().slice(0,10),endDate:end.toISOString().slice(0,10),dimension:'query'})});const v=await r.json();if(!r.ok)throw new Error(v.error);const report=readOverviewPerformance(v.data);setRows(report.rows);setSummary(report.summary);setStatus('done')}catch{setStatus('error')}}
  const totals={clicks:summary.clicks,impressions:summary.impressions};
  return <><PropertyPicker onChange={load}/>{status==='loading'&&<ReportState kind="loading" title="Loading report" message="Requesting Search Console data…"/>}{status==='error'&&<ReportState kind="error" title="Report unavailable" message="Check the Google connection and property permission."/>}{status==='idle'&&<ReportState kind="empty" title="Select a property" message="Choose a Search Console property to load the report."/>}{status==='done'&&<><div className="metrics"><Metric label="Clicks" value={totals.clicks.toLocaleString()}/><Metric label="Impressions" value={totals.impressions.toLocaleString()}/><Metric label="Average CTR" value={totals.impressions?`${(totals.clicks/totals.impressions*100).toFixed(1)}%`:'0%'}/><Metric label="Queries" value={rows.length.toString()}/></div>{!compact&&<div className="card"><div className="card-head"><div><span>Top queries</span><h2>Organic search performance</h2></div><small>Last 28 days</small></div>{rows.length?<table><thead><tr><th>Query</th><th>Clicks</th><th>Impressions</th><th>CTR</th><th>Position</th></tr></thead><tbody>{rows.map(r=><tr key={r.key}><td>{r.key}</td><td>{r.clicks}</td><td>{r.impressions}</td><td>{(r.ctr*100).toFixed(1)}%</td><td>{r.position.toFixed(1)}</td></tr>)}</tbody></table>:<ReportState kind="empty" title="No performance rows" message="Google returned no queries for this period."/>}</div>}</>}</>;
}
export function Metric({label,value}:{label:string;value:string}){return <div className="metric" title={`${label} for the selected reporting period`}><span>{label}</span><strong>{value}</strong><small>Selected period</small></div>}
export function InspectionPanel(){const [property,setProperty]=useState('');const [result,setResult]=useState<unknown>();const [error,setError]=useState('');async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const url=String(new FormData(e.currentTarget).get('url'));const r=await fetch('/api/inspect',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({property,url})});const v=await r.json();if(r.ok){setResult(v.data);setError('')}else setError(v.error)}return <><PropertyPicker onChange={setProperty}/><form className="inspect-form" onSubmit={submit}><label>Fully qualified URL<input name="url" type="url" placeholder="https://example.com/page" required/></label><button disabled={!property}>Inspect indexed URL</button></form>{error&&<ReportState kind="error" title="Inspection unavailable" message={error}/>} {!!result&&<pre className="result">{JSON.stringify(result,null,2)}</pre>}<p className="notice">This reports the version in Google&apos;s index. It is not a live test and cannot request indexing.</p></>}
type VitalsData={status:"available"|"insufficient-data";metrics:Array<{name:string;value:number;unit:string;rating:string}>};
export function VitalsPanel(){const [value,setValue]=useState('');const [data,setData]=useState<VitalsData>();async function submit(e:React.FormEvent){e.preventDefault();const r=await fetch('/api/vitals',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({value,mode:'origin'})});setData((await r.json()).data)}return <><form className="inspect-form" onSubmit={submit}><label>Website origin<input value={value} onChange={e=>setValue(e.target.value)} type="url" placeholder="https://example.com" required/></label><button>Check field data</button></form>{data?.status==='insufficient-data'&&<ReportState kind="empty" title="Insufficient field data" message="CrUX has no record for this origin."/>}<div className="metrics">{data?.metrics?.map(m=><div className={`metric vital-${m.rating}`} key={m.name}><span>{m.name}</span><strong>{m.value}{m.unit}</strong><small>{m.rating.replace('-',' ')}</small></div>)}</div><p className="notice">CrUX contains aggregated real-user data from a rolling 28-day window.</p></>}
