"use client";
import { useEffect, useMemo, useState } from "react";
import { LocationPicker } from "./location-picker";
import { KeywordManager, type KeywordView } from "./keyword-manager";
import type { AnalyticsReport, LocationOption } from "./types";

const total=(values:Array<{value:number}>)=>values.reduce((sum,point)=>sum+point.value,0);
function isoDaysAgo(days:number){const date=new Date();date.setUTCDate(date.getUTCDate()-days);return date.toISOString().slice(0,10);}
export function GbpAnalytics(){
  const [locations,setLocations]=useState<LocationOption[]>([]),[locationId,setLocationId]=useState(""),[report,setReport]=useState<AnalyticsReport>(),[keywords,setKeywords]=useState<KeywordView[]>([]),[error,setError]=useState(""),[stale,setStale]=useState(false);
  useEffect(()=>{fetch("/api/gbp/locations").then(r=>r.json()).then(v=>setLocations(v.data??[])).catch(()=>setError("Unable to load Business Profile locations."));},[]);
  useEffect(()=>{if(!locationId)return;const query=new URLSearchParams({locationId,startDate:isoDaysAgo(27),endDate:new Date().toISOString().slice(0,10)});Promise.all([fetch(`/api/gbp/analytics?${query}`).then(r=>r.json()),fetch(`/api/gbp/keywords?locationId=${encodeURIComponent(locationId)}`).then(r=>r.json())]).then(([analytics,tracked])=>{if(!analytics.data)throw new Error();setReport(analytics.data);setStale(Boolean(analytics.stale));setKeywords(tracked.data??[]);setError("");}).catch(()=>setError("Business Profile analytics are unavailable."));},[locationId]);
  const cards=useMemo(()=>report?[{label:"Impressions",value:total(report.daily.impressions)},{label:"Calls",value:total(report.daily.calls)},{label:"Directions",value:total(report.daily.directions)},{label:"Website clicks",value:total(report.daily.websiteClicks)}]:[],[report]);
  async function add(keyword:string,source:"MANUAL"|"GBP_SUGGESTED"="MANUAL"){const response=await fetch("/api/gbp/keywords",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({locationId,keyword,source})});const value=await response.json();if(response.ok)setKeywords(current=>[...current.filter(item=>item.id!==value.data.id),value.data]);}
  async function update(id:string,state:"APPROVED"|"PAUSED"){const response=await fetch("/api/gbp/keywords",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,state})});const value=await response.json();if(response.ok)setKeywords(current=>current.map(item=>item.id===id?value.data:item));}
  return <div className="local-seo-workspace"><div className="local-controls"><LocationPicker value={locationId} onChange={setLocationId} locations={locations}/></div>{error&&<div className="state state-error"><strong>Analytics unavailable</strong><span>{error}</span></div>}{stale&&<div className="state state-stale"><strong>Showing cached data</strong><span>Google is temporarily unavailable.</span></div>}{!locationId&&!error&&<p className="notice">Choose a Business Profile location to load official analytics.</p>}{report&&<><p className="notice">Official Google Business Profile data · last 28 days</p><div className="metrics">{cards.map(card=><div className="metric" key={card.label}><span>{card.label}</span><strong>{card.value.toLocaleString()}</strong><small>Selected location</small></div>)}</div><div className="local-grid"><div className="card"><div className="card-head"><div><span>Discovery</span><h2>Search queries</h2></div></div>{report.searchQueries.length?<table><thead><tr><th>Query</th><th>Impressions</th><th>Tracking</th></tr></thead><tbody>{report.searchQueries.map(query=><tr key={query.keyword}><td>{query.keyword}</td><td>{query.impressions}</td><td><button onClick={()=>add(query.keyword,"GBP_SUGGESTED")}>Track</button></td></tr>)}</tbody></table>:<p className="notice">No monthly search-query data is available.</p>}</div><div className="card"><div className="card-head"><div><span>Geo-grid preparation</span><h2>Tracked keywords</h2></div></div><KeywordManager keywords={keywords} onAdd={add} onUpdate={update}/></div></div></>}</div>;
}
