"use client";
import { Area, CartesianGrid, ComposedChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import type { ReportRow } from "./types";
const compact=(v:number)=>Intl.NumberFormat("en",{notation:"compact",maximumFractionDigits:1}).format(v);
function dateLabel(v:string){const d=new Date(v.includes("T")?v:`${v}T00:00:00Z`);return Number.isNaN(d.valueOf())?v:d.toLocaleDateString("en-US",{month:"short",day:"numeric",timeZone:"UTC"})}
// Recharts requires a small renderer factory so each series can own its marker color.
// eslint-disable-next-line react/display-name
const marker=(color:string)=>(p:{cx?:number;cy?:number})=>p.cx==null||p.cy==null?null:<circle cx={p.cx} cy={p.cy} r="3.8" fill="#fff" stroke={color} strokeWidth="2"/>;
export function PerformanceChart({rows}:{rows:ReportRow[]}){return <div className="chart-wrap"><div className="performance-chart" aria-label="Clicks and impressions gradient area chart"><ResponsiveContainer width="100%" height={410}><ComposedChart data={rows} margin={{top:24,right:10,left:4,bottom:12}}><defs><linearGradient id="cyanArea" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#08c5d9" stopOpacity={.56}/><stop offset="70%" stopColor="#3dd4df" stopOpacity={.2}/><stop offset="100%" stopColor="#eafcff" stopOpacity={.03}/></linearGradient><linearGradient id="pinkArea" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#ff4fad" stopOpacity={.5}/><stop offset="68%" stopColor="#ff81c4" stopOpacity={.18}/><stop offset="100%" stopColor="#fff0f8" stopOpacity={.02}/></linearGradient></defs><CartesianGrid stroke="#dce5ed" strokeDasharray="2 5" vertical={false}/><XAxis dataKey="key" tickFormatter={dateLabel} tick={{fontSize:11,fill:"#7b8da0"}} tickLine={false} axisLine={{stroke:"#8493a4"}} minTickGap={38}/><YAxis yAxisId="clicks" width={42} tick={{fontSize:11,fill:"#7890a3"}} tickLine={false} axisLine={false} allowDecimals={false}/><YAxis yAxisId="impressions" orientation="right" width={48} tickFormatter={compact} tick={{fontSize:11,fill:"#7890a3"}} tickLine={false} axisLine={false}/><Tooltip labelFormatter={label=>dateLabel(String(label??""))} formatter={(value,name)=>[Number(value).toLocaleString(),name==="clicks"?"Clicks":"Impressions"]} contentStyle={{borderRadius:14,border:"1px solid #dbe4ec",boxShadow:"0 16px 42px rgba(21,43,68,.16)",padding:"12px 16px"}} cursor={{stroke:"#9eb0bf",strokeDasharray:"3 5"}}/><Area yAxisId="impressions" type="monotone" dataKey="impressions" stroke="#ff4fad" strokeWidth={2.2} fill="url(#pinkArea)" dot={marker("#ff4fad")} activeDot={{r:5,fill:"#fff",stroke:"#ff4fad",strokeWidth:2.5}}/><Area yAxisId="clicks" type="monotone" dataKey="clicks" stroke="#08bdd2" strokeWidth={2.3} fill="url(#cyanArea)" dot={marker("#08bdd2")} activeDot={{r:5,fill:"#fff",stroke:"#08bdd2",strokeWidth:2.5}}/></ComposedChart></ResponsiveContainer></div><div className="chart-legend chart-legend-bottom"><span className="clicks"><i/>Clicks</span><span className="impressions"><i/>Impressions</span></div></div>}
